name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: Add Lua PPA
      run: add-apt-repository -y ppa:lua/ubuntu
    - name: Install liblua
      run: apt-get install -y liblua5.4-dev
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
